-- AI image generation fields for brand_images
-- Tracks which images were AI-generated, what prompt/model was used,
-- and which scraped brand assets were passed as reference images.

ALTER TABLE brand_images
  ADD COLUMN IF NOT EXISTS is_ai_generated  BOOLEAN   DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS generation_prompt TEXT,
  ADD COLUMN IF NOT EXISTS reference_image_ids UUID[],
  ADD COLUMN IF NOT EXISTS model             TEXT,
  ADD COLUMN IF NOT EXISTS provider          TEXT,
  ADD COLUMN IF NOT EXISTS storage_path      TEXT;     -- path in Supabase Storage bucket

-- Index for filtering AI-generated images per brand
CREATE INDEX IF NOT EXISTS idx_brand_images_ai
  ON brand_images(brand_id, is_ai_generated)
  WHERE is_ai_generated = TRUE;

COMMENT ON COLUMN brand_images.is_ai_generated    IS 'True if this image was generated by an AI model';
COMMENT ON COLUMN brand_images.generation_prompt  IS 'The prompt used to generate this image';
COMMENT ON COLUMN brand_images.reference_image_ids IS 'IDs of brand_images rows used as reference inputs';
COMMENT ON COLUMN brand_images.model              IS 'Model ID used, e.g. gemini-2.5-flash-image';
COMMENT ON COLUMN brand_images.provider           IS 'Provider ID, e.g. gemini, imagen, fal';
COMMENT ON COLUMN brand_images.storage_path       IS 'Path in Supabase Storage: generated-images/{brand_id}/{id}.png';
